Fabricator(:client, from: Billink::Client) do
  company_name  "Acme Corp."
  kvk_number    "01234567"
  first_name    "John"
  last_name     "Doe"
  initials      "J.A."
  sex           "M"
  street        "Damrak"
  city          "Amsterdam"
  house_number  "1"
  house_number_extension ""
  postal_code   "1234AB"
  phone_number  "0612345678"
  birth_date    "01-01-1990"
  email         "john@example.com"
  order_amount  "1"
end
